# Generated by Django 6.0.6 on 2026-06-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('transferencia', 'Transferencia'), ('bizum', 'Bizum'), ('liquidacion_cuenta', 'Liquidación de cuenta')], max_length=30)),
                ('categoria', models.CharField(choices=[('nomina', 'Nómina'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('ocio', 'Ocio'), ('compras', 'Compras'), ('suministros', 'Suministros'), ('transferencia', 'Transferencia'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cuentas.cuenta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
