# Generated by Django 6.0.6 on 2026-07-20 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('prestamo_online', 'Préstamo online'), ('tarjeta', 'Tarjeta'), ('cuenta_adicional', 'Cuenta adicional'), ('cuenta_ahorro', 'Cuenta de ahorro'), ('cuenta_menor', 'Cuenta menor de edad')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_estudio', 'En estudio'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('importe_solicitado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plazo_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('finalidad', models.CharField(blank=True, max_length=200)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_productos', to='cuentas.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de producto',
                'verbose_name_plural': 'Solicitudes de productos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
