# Generated by Django 6.0.6 on 2026-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=24, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Cuenta corriente'), ('ahorro', 'Cuenta de ahorro')], default='corriente', max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
